name: Build Blend2D and pack Blend2NET

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            os_name: win
            architecture: x64
            rid: win-x64
          - os: windows-latest
            os_name: win
            architecture: amd64_arm64
            rid: win-arm64
          - os: ubuntu-latest
            os_name: linux
            architecture: x64
            rid: linux-x64
          - os: ubuntu-24.04-arm
            os_name: linux-arm64
            architecture: aarch64
            rid: linux-arm64
          - os: macos-13
            os_name: osx
            architecture: x64
            rid: osx-x64
          - os: macos-latest
            os_name: osx
            architecture: arm64
            rid: osx-arm64
    name: Build ${{ matrix.os_name }} ${{ matrix.architecture }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies (Linux)
        if: ${{matrix.os_name == 'linux' || matrix.os_name == 'linux-arm64'}}
        run: |
          sudo apt update
          sudo apt install -y ninja-build
          

      - name: Install Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install ninja -y
      - if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture }}
          sdk: "10.0.19041.0"

      - name: Install Dependencies (Mac)
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'macos-13' }}
        run: |
          brew install ninja

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -G Ninja -DRID=${{ matrix.rid }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }} -S ${{ github.workspace }} -B ${{ github.workspace }}/build

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: ninja -j 4

      - name: Install
        working-directory: ${{ github.workspace }}/build
        run: ninja install

      - name: Upload shared library
        uses: actions/upload-artifact@v4
        with:
          name: lib-${{ matrix.rid }}
          path: ${{ github.workspace }}/runtimes

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Download built libs
        uses: actions/download-artifact@v4
        with:
          pattern: lib-*
          path: ${{ github.workspace }}/runtimes
          merge-multiple: true
      - name: Create NuGet package
        shell: bash
        working-directory: ${{ github.workspace }}
        run: dotnet build -c Release

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: Blend2NET
          path: ${{ github.workspace }}/bin/Release/*.s?nupkg