name: Build Blend2D and pack Blend2NET

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            os_name: win
            architecture: x64
            rid: win-x64
          - os: windows-latest
            os_name: win
            architecture: x86
            rid: win-x86
          - os: windows-latest
            os_name: win
            architecture: arm64
            rid: win-arm64
          - os: ubuntu-latest
            os_name: linux
            architecture: x64
            rid: linux-x64
          - os: ubuntu-latest
            os_name: linux-musl
            architecture: x64
            rid: linux-musl-x64
          - os: ubuntu-latest
            os_name: linux-musl
            architecture: arm64
            rid: linux-musl-arm64
          - os: ubuntu-latest
            os_name: linux-arm
            architecture: armv7l
            rid: linux-arm
          - os: ubuntu-latest
            os_name: linux-arm64
            architecture: aarch64
            rid: linux-arm64
          - os: macos-latest
            os_name: osx
            architecture: x64
            rid: osx-x64
          - os: macos-latest
            os_name: osx
            architecture: arm64
            rid: osx-arm64
    name: Build ${{ matrix.os_name }} ${{ matrix.architecture }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          if [[ "${{ matrix.os_name }}" == "linux-musl" ]]; then
            sudo apt install -y musl-dev zlib1g-dev
          elif [[ "${{ matrix.os_name }}" == "linux-arm" ]]; then
            sudo apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          elif [[ "${{ matrix.os_name }}" == "linux-arm64" ]]; then
            sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          fi

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake -DRID=${{ matrix.rid }} -DCMAKE_INSTALL_PREFIX=${{ github.workspace }} -S ${{ github.workspace }} -B ${{ github.workspace }}/build

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config Release -j 2

      - name: Install
        working-directory: ${{ github.workspace }}/build
        run: cmake --install . --config Release

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Create NuGet package
        shell: bash
        working-directory: ${{ github.workspace }}
        run: dotnet pack Blend2NET.csproj -c Release -o 

      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: Blend2NET
          path: ${{ github.workspace }}/*.nupkg